"""
Resend email service wrapper.
"""
import asyncio
import logging
import resend

from app.config import settings

logger = logging.getLogger(__name__)

resend.api_key = settings.RESEND_API_KEY


def wrap_digest_html(content_html: str, period_label: str) -> str:
    """Wrap Claude-assembled digest content in a full HTML email template."""
    frontend_url = settings.FRONTEND_URL
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    @media (max-width: 600px) {{
      .outer {{ padding: 0 !important; }}
      .card {{ border-radius: 0 !important; border-left: none !important; border-right: none !important; }}
      .body {{ padding: 24px 20px !important; }}
    }}
  </style>
</head>
<body style="margin:0;padding:0;background-color:#F7F6F3;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div class="outer" style="max-width:600px;margin:40px auto;padding:0 16px;">
    <div class="card" style="background:#ffffff;border:1px solid #E2E0DB;border-radius:4px;overflow:hidden;">

      <!-- Header -->
      <div style="background:#0C0C0C;padding:24px 32px;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-family:Georgia,'Times New Roman',serif;font-size:22px;color:#F0EEE9;letter-spacing:-0.01em;font-weight:400;">Donna</span>
        <span style="color:#C0392B;font-family:monospace;font-size:10px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;">{period_label}</span>
      </div>

      <!-- Body -->
      <div class="body" style="padding:32px;color:#111111;font-size:14px;line-height:1.65;">
        {content_html}
      </div>

      <!-- Footer -->
      <div style="background:#F7F6F3;padding:16px 32px;border-top:1px solid #E2E0DB;">
        <p style="font-size:11px;color:#737373;margin:0;">
          Generated by Donna &mdash; Always three steps ahead.
          &middot;
          <a href="{frontend_url}/settings" style="color:#737373;text-decoration:underline;">Adjust preferences</a>
          &middot;
          <a href="{frontend_url}/settings" style="color:#737373;text-decoration:underline;">Unsubscribe</a>
        </p>
      </div>

    </div>
  </div>
</body>
</html>"""


async def send_email(
    to: str,
    subject: str,
    html: str,
    text: str | None = None,
) -> bool:
    if not to or not to.strip():
        logger.warning("Skipping email send: no recipient address")
        return False

    try:
        params: resend.Emails.SendParams = {
            "from": settings.RESEND_FROM_EMAIL,
            "to": [to],
            "subject": subject,
            "html": html,
        }
        if text:
            params["text"] = text

        # Run synchronous Resend SDK in thread pool to avoid blocking event loop
        await asyncio.to_thread(resend.Emails.send, params)
        logger.info(f"Email sent to {to}: {subject}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email to {to}: {e}")
        return False
